Repository shenoy-anurag/simple-reddit, pull requests merged in 2022-04, with the labels that each got.

#160 feat, fix: Feed API + Delete Profile API + delete user
  backend/communities/service.go
  backend/posts/models.go
  backend/posts/service.go
  backend/profiles/models.go
  backend/profiles/service.go
  backend/users/service.go
Labels: enhancement, User Stories - BE, User Story, sprint3, hard

#177 enhancement: FeedAPI URL method changed to POST from GET
  backend/posts/service.go
  backend/profiles/service.go
Labels: enhancement, User Stories - FE, User Story, easy, sprint3

#181 feat: api to upvote/downvote, maintaining history of voting
  backend/comments/models.go
  backend/comments/service.go
  db.zip
Labels: enhancement, User Stories - BE, User Story, sprint3

#182 feat, refactor, fix: DeleteProfile API + delete user functionality, optimized most of the API in profiles, communities
  backend/communities/service.go
  backend/profiles/models.go
  backend/profiles/service.go
Labels: User Stories - BE, User Story, sprint3, bugfix, hard

#196 docs,chore: created sprint3.md and updated readme, changed non-post http methods to post
  README.md
  Sprint3.md
  backend/communities/service.go
Labels: documentation, sprint3

#199 feat: api to get all communities
  backend/communities/service.go
Labels: User Stories - BE, User Story, sprint3

#206 feat,fix: new api to get comments for post, voting bug fixed
  backend/comments/models.go
  backend/comments/service.go
  backend/common/error_msgs.go
  backend/communities/service.go
  backend/posts/models.go
Labels: bug, enhancement, User Stories - BE, User Story, sprint3

#205 feat: Vote API + Readability
  backend/posts/models.go
  backend/posts/service.go
  backend/profiles/models.go
  backend/profiles/service.go
Labels: User Stories - BE, User Story, sprint3, bugfix, medium

#215 build,feat,docs: go mod tidy, added pagination in get all communities…
  Sprint3.md
  backend/communities/models.go
  backend/communities/service.go
  backend/go.mod
  backend/go.sum
Labels: documentation, User Stories - BE, User Story, easy, sprint3

#216 feat: Delete Saved integrated onto DeleteProfile API
  backend/posts/service.go
  backend/profiles/service.go
  backend/users/models.go
Labels: enhancement, User Stories - BE, bugfix, medium

#224 feat, enhancement: DeleteProfile API updated, SavedComment created
  backend/communities/service.go
  backend/profiles/models.go
  backend/profiles/service.go
Labels: enhancement, User Stories - BE, sprint3, medium

#227 docs: removed unnecessary line
  Sprint3.md
Labels: documentation

#231 gotests: test cases for profiles,post and saved
  backend/tests/comments_tests.go
  backend/tests/profile_tests.go
  backend/tests/saved_tests.go
Labels: User Stories - BE, User Story, sprint3

#235 gotest: removed the file
  backend/tests/comments_tests.go
Labels: duplicate, invalid, sprint3, test

#238 test: tests for create, get, vote and delete comments
  backend/comments/models.go
  backend/comments/service.go
  backend/tests/comments_test.go
  backend/tests/main_test.go
  backend/tests/posts_test.go
Labels: User Stories - BE, User Story, test, sprint4

#253 feat : GetSubcriptions and UpdateSubscriptions
  backend/communities/service.go
  backend/profiles/service.go
  backend/users/models.go
  backend/users/service.go
Labels: enhancement, User Stories - BE, User Story, sprint4, hard

#259 feat, enhancement: Created GetSavedPosts API, enhanced UpdateSavedPosts and UpdateSavedComments API
  backend/profiles/models.go
  backend/profiles/service.go
Labels: enhancement, User Stories - BE, User Story, sprint4, hard

#266 Updated features sections
  README.md
Labels: documentation, User Story, sprint4

#270 ci: aws deployment appspec file added
  appspec.yml
Labels: enhancement, sprint4, hard

#271 Wrote install dependencies and validate service scripts
  appspec.yml
  scripts/after_install.sh
  scripts/create_test_db.sh
  scripts/install_dependencies.sh
  scripts/start_server.sh
  scripts/stop_server.sh
  scripts/validate_service.sh
Labels: enhancement, sprint4

#272 Created gihtub workflow for ci/cd
  .github/workflows/ci-cd-pipeline.yml
Labels: enhancement, sprint4

#273 created github workflow for ci/cd
  .github/workflows/ci-cd-aws.yml
Labels: enhancement, sprint4

#281 Added stop server commands, fixed AWSCodeDeploy github workflow
  .github/workflows/ci-cd-aws.yml
  .github/workflows/ci-cd-pipeline.yml
  scripts/start_server.sh
  scripts/stop_server.sh
Labels: enhancement, easy, sprint4

#282 ci: updated install scripts, added role to assume in workflow
  .github/workflows/ci-cd-aws.yml
  appspec.yml
  scripts/after_install.sh
  scripts/before_install.sh
  scripts/install_dependencies.sh
Labels: enhancement, sprint4

#286 ci: fixed scripts, added systemd service for backend, removed go run …
  .github/workflows/ci-cd-aws.yml
  appspec.yml
  scripts/after_install.sh
  scripts/before_install.sh
  scripts/simple-reddit-backend.service
  scripts/start_server.sh
  scripts/stop_server.sh
Labels: enhancement, sprint4, hard

#280 refactor,style: added better error handling for no documents
  backend/comments/service.go
  backend/communities/service.go
  backend/posts/models.go
  backend/posts/service.go
  backend/profiles/models.go
  backend/profiles/service.go
  backend/users/models.go
  backend/users/service.go
Labels: easy, bugfix, sprint4

#290 feat: Created GetSubscribers API , GetSaved Comment API and modified the UpdateSubscription API
  backend/communities/models.go
  backend/communities/service.go
  backend/profiles/models.go
  backend/profiles/service.go
  backend/users/models.go
  backend/users/service.go
Labels: enhancement, User Stories - BE, User Story, bugfix, sprint4, medium, hard

#291 fix : checkname API and GetCommunity API
  backend/communities/service.go
  backend/profiles/service.go
Labels: documentation, User Stories - BE, User Story, easy, bugfix, sprint4, hard

#297 Created CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, User Story, sprint4, medium, low priority

#299 Added Steps for backend setup and frontend setup
  CONTRIBUTING.md
Labels: documentation, User Stories - FE, User Stories - BE, User Story, easy, sprint4, low priority

#301 Create CODE OF CONDUCT for Contributors
  CODE_OF_CONDUCT.md
Labels: documentation, User Story, easy, sprint4, low priority

#302 docs: added aws ci/cd workflow badge, app url
  README.md
Labels: documentation, sprint4

#329 docs: added Sprint4.md structure
  Sprint4.md
Labels: documentation

#330 ci,chore: updated after install and start server scripts for frontend…
  db.zip
  scripts/after_install.sh
  scripts/start_server.sh
Labels: sprint4

#331 ci: added frontend deployment to ci/cd pipeline
  .github/workflows/ci-cd-aws.yml
  scripts/after_install.sh
  scripts/start_server.sh
Labels: enhancement

#334 ci: fixed s3 upload error, added aws cli install for s3 download
  .github/workflows/ci-cd-aws.yml
  scripts/before_install.sh
Labels: enhancement

#335 Update Sprint4.md
  Sprint4.md
Labels: documentation, User Stories - BE, easy, test, sprint4

#337 fix,test: removed tests with syntax errors and added profile crud tests
  .github/workflows/go-tests.yml
  backend/profiles/service.go
  backend/tests/main_test.go
  backend/tests/profile_test.go
  backend/tests/profile_tests.go
  backend/tests/saved_tests.go
Labels: enhancement

#342 bugfix, fix: Saved Items API Reponses modified
  backend/profiles/models.go
Labels: User Stories - BE, User Story, bugfix, sprint4, medium

#343 Added Sprint4.md link
  README.md
Labels: documentation, easy

#347 docs: added go tests badge, formatting
  README.md
Labels: documentation, sprint4

#353 fix: unlimited votes by single user, only creator can vote
  backend/posts/models.go
  backend/posts/service.go
Labels: bugfix, sprint4, medium

#354 fix: comment delete route changed to POST method
  backend/comments/service.go
  backend/tests/comments_test.go
Labels: bugfix

#356 docs: added short Testing Video and API Demo video
  Sprint4.md
Labels: documentation, easy, sprint4

#368 fix: uncommented api to get posts of community
  backend/communities/service.go
Labels: User Stories - BE, bugfix, sprint4
