Repository shenoy-anurag/simple-reddit, pull requests merged in 2022-03, with the labels that each got.

#73 feat,refactor: added check-name, edit, delete community apis, moved responses to new pkg
  backend/common/error_msgs.go
  backend/common/response.go
  backend/common/success_msgs.go
  backend/communities/models.go
  backend/communities/service.go
  backend/posts/models.go
  backend/posts/service.go
  backend/users/service.go
Labels: enhancement, User Stories - BE, User Story

#77 fix: GetAllPosts API is fixed
  backend/posts/service.go
Labels: User Stories - BE

#79 feat,refactor,test: added acceptance and unit testing, added routes package
  backend/communities/service.go
  backend/configs/dbSetup.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/posts/service.go
  backend/routes/routes.go
  backend/test_utils/constants.go
  backend/test_utils/make_request.go
  backend/tests/Readme.md
  backend/tests/main_test.go
  backend/tests/ping_test.go
  backend/tests/users_test.go
  backend/users/service.go
Labels: enhancement

#90 feat: Deletepost and GetAllPost API Editpost API
  backend/posts/models.go
  backend/posts/service.go
Labels: User Stories - BE

#83 ci,refactor: added go tests workflow, improved code formatting
  .github/workflows/go-tests.yml
  backend/communities/models.go
  backend/communities/service.go
  backend/configs/LoginService.go
  backend/configs/env.go
  backend/posts/models.go
  backend/profiles/models.go
  backend/test_utils/constants.go
  backend/users/models.go
  backend/users/service.go
Labels: documentation

#92 feat: created profile API, integrated into signup API
  backend/profiles/models.go
  backend/profiles/service.go
  backend/users/models.go
  backend/users/service.go
Labels: User Stories - BE

#96 feat,gotest,refactor: GetProfile API created, go-test for posts, improved readability
  backend/posts/service.go
  backend/profiles/models.go
  backend/profiles/service.go
  backend/routes/routes.go
  backend/tests/posts_test.go
  backend/users/models.go
Labels: User Stories - BE

#98 feat: profile details for a username can be updated using EditProfile API
  backend/profiles/models.go
  backend/profiles/service.go
Labels: User Stories - BE

#106 feat, fix: GetAllCommunities API created, API created to GetAllposts for a community, GetProfile API
  backend/communities/models.go
  backend/communities/service.go
  backend/profiles/models.go
Labels: enhancement, User Stories - BE

#108 feat: API to fetch all posts for the home page
  backend/posts/service.go
Labels: enhancement, User Stories - BE

#116 fix: checkCommunityExist API response message was correctly set to API_SUCCESS
  backend/communities/service.go
Labels: enhancement

#118 fix: editCommunity API updates the community after checking if it exists
  backend/communities/service.go
Labels: bug

#119 docs: created sprint2.md explaining functionalities and user stories
  Sprint2.md
Labels: documentation

#120 docs: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: documentation

#121 docs: added links to sprints documentation
  README.md
Labels: documentation

#130 feat, fix: request and logic flow for GetAllCommunitites and GetCommunity API
  backend/communities/models.go
  backend/communities/service.go
  backend/go.mod
  backend/go.sum
Labels: User Stories - BE, sprint3, bugfix, hard

#136 docs: updated readme with backend/frontend dev sections
  README.md
Labels: documentation

#157 feat, bugfix: Feed API to fetch posts in a paginated manner
  backend/communities/models.go
  backend/posts/models.go
  backend/posts/service.go
Labels: enhancement, User Stories - BE, User Story, sprint3, bugfix, medium

#162 feat: api for adding comments to posts
  backend/comments/models.go
  backend/comments/service.go
  backend/communities/service.go
  backend/routes/routes.go
  backend/tests/posts_test.go
Labels: enhancement, User Stories - BE, User Story

#168 feat: api to delete comments, parent comment validation
  backend/comments/models.go
  backend/comments/service.go
  backend/common/error_msgs.go
Labels: enhancement, User Stories - BE, User Story, sprint3
